export const bookingConstants = {
  BOOKING_ITEMS_ADD: 'BOOKING_ITEMS_ADD',
  NEW_BOOKING_REQUEST: 'NEW_BOOKING_REQUEST',
  NEW_BOOKING_SUCCESS: 'NEW_BOOKING_SUCCESS',
  NEW_BOOKING_FAIL: 'NEW_BOOKING_FAIL',
}
