export const bookingConstants = {
  BOOKING_ITEMS_ADD: 'BOOKING_ITEMS_ADD',
  NEW_BOOKING_REQUEST: 'NEW_BOOKING_REQUEST',
  NEW_BOOKING_SUCCESS: 'NEW_BOOKING_SUCCESS',
  NEW_BOOKING_FAIL: 'NEW_BOOKING_FAIL',
  THEATRE_BOOKINGS_REQUEST: 'THEATRE_BOOKINGS_REQUEST',
  THEATRE_BOOKINGS_SUCCESS: 'THEATRE_BOOKINGS_SUCCESS',
  THEATRE_BOOKINGS_FAIL: 'THEATRE_BOOKINGS_FAIL',
  USER_BOOKINGS_REQUEST: 'USER_BOOKINGS_REQUEST',
  USER_BOOKINGS_SUCCESS: 'USER_BOOKINGS_SUCCESS',
  USER_BOOKINGS_FAIL: 'USER_BOOKINGS_FAIL',
}
