export const seatConstants = {
  SEAT_CONFIRMATION_REQUEST: 'SEAT_CONFIRMATION_REQUEST',
  SEAT_CONFIRMATION_SUCCESS: 'SEAT_CONFIRMATION_SUCCESS',
  SEAT_CONFIRMATION_FAIL: 'SEAT_CONFIRMATION_FAIL',
  SEAT_RESERVED_CLEARANCE_REQUEST: 'SEAT_RESERVED_CLEARANCE_REQUEST',
  SEAT_RESERVED_CLEARANCE_SUCCESS: 'SEAT_RESERVED_CLEARANCE_SUCCESS',
  SEAT_RESERVED_CLEARANCE_FAIL: 'SEAT_RESERVED_CLEARANCE_REQUEST',
  SEAT_BOOKING_REQUEST: 'SEAT_BOOKING_REQUEST',
  SEAT_BOOKING_SUCCESS: 'SEAT_BOOKING_SUCCESS',
  SEAT_BOOKING_FAIL: 'SEAT_BOOKING_FAIL',
}
