export const theatreConstants = {
  THEATRES_LIST_REQUEST: 'THEATRES_LIST_REQUEST',
  THEATRES_LIST_SUCCESS: 'THEATRES_LIST_SUCCESS',
  THEATRES_LIST_FAIL: 'THEATRES_LIST_FAIL',
  THEATRE_BY_ID_REQUEST: 'THEATRE_BY_ID_REQUEST',
  THEATRE_BY_ID_SUCCESS: 'THEATRE_BY_ID_SUCCESS',
  THEATRE_BY_ID_FAIL: 'THEATRE_BY_ID_FAIL',
  ADD_THEATRE_REQUEST: 'ADD_THEATRE_REQUEST',
  ADD_THEATRE_SUCCESS: 'ADD_THEATRE_SUCCESS',
  ADD_THEATRE_FAIL: 'ADD_THEATRE_FAIL',
}
