export const verificationConstants = {
  VERIFICATION_EMAIL_REQUEST: 'VERIFICATION_EMAIL_REQUEST',
  VERIFICATION_EMAIL_SUCCESS: 'VERIFICATION_EMAIL_SUCCESS',
  VERIFICATION_EMAIL_FAIL: 'VERIFICATION_EMAIL_FAIL',
}
